version: '3.8'

services:
    db:
        image: mariadb:10.6
        container_name: sulu-app-db
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        ports:
            - "3306:3306"
        volumes:
            - ./db/data:/var/lib/mysql

    mailer:
        image: schickling/mailcatcher
        container_name: sulu-app-mailer
        ports:
            - "1080:1080"
            - "1025:1025"